### ISSUE TITLE
Increase speed counter TweetCard

### ISSUE THREAD

**Issue by Laguilavo10** [serudda/twon#20]
### What problem does your feature request solve?

When accessing the landing page, the load time of the view counter for the tweet on the right is very long, with an approximate duration of 1 minute and 34 seconds.

### Describe the solution you'd like

In my opinion, it is recommended to increase the speed of the counter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by serudda** [comment]
DONE
https://github.com/serudda/twon/pull/22
